name: Deploy to sffnoobs environment on push to main

on:
  push:
    branches: [ main ]
    paths:
      - 'force-app/**'

jobs:
  Deploy-to-sffnoobs-environment:
      runs-on: ubuntu-latest
      environment: sffnoobs
      steps:
          - uses: actions/setup-node@v3
            with:
              node-version: '18'
          - name: 'Checkout source code'
            uses: actions/checkout@v3
            with:
              fetch-depth: '2'
                
          # Now Install Salesforce CLI
          - name: 'Install sfdx'
            run: npm install @salesforce/cli --global
          - name: 'Installing sfdx git delta'
            run: | 
                echo Y | sfdx plugins:install sfdx-git-delta
                sfdx plugins

          - name: 'Create delta packages'
            run: | 
                mkdir changed-sources
                sf sgd source delta --to "HEAD" --from "HEAD~1" --output changed-sources/ --generate-delta --source force-app/
                echo "[INFO] Diff generated"
                
          - name: 'Deploy to environment with running all local tests'
            run: |
                echo "${{ secrets.SF_JWT_KEY }}" > server.key
                sf org login jwt --username ${{ secrets.SF_USERNAME_QA }} --jwt-key-file server.key --client-id ${{ secrets.SF_CLIENT_ID }} --instanceurl https://login.salesforce.com \
                sf project deploy start --source-dir changed-sources/force-app --test-level RunLocalTests --target-org ${{ secrets.SF_USERNAME_QA }}
